#!/usr/bin/env python3
"""Generate contracts/fixtures/*.json for FPT and KDH.

Usage (from repository root):
    python contracts/fixtures/generate_fixtures.py

Owner: Lead integrator (contracts/OWNERSHIP.md). These fixtures are the WP0
deliverable "sufficient for the frontend and quantitative agents to develop
with no backend present" (P0 prompt, deliverable 4). They are SYNTHETIC
development data, not a real market feed. See contracts/fixtures/README.md.

The only real, plan-verified values used anywhere in these fixtures are the
FPT bar for 2026-07-30, taken directly from the Section 10.1 example in
vn_terminal_multi_ai_development_plan.md v1.1:
    O 65.2, H 67.2, L 64.8, C 67.0, V 7,571,500

Every other number in every fixture file is synthetically generated with a
fixed random seed for reproducibility, and every response envelope's
provenance.warnings says so explicitly.
"""

from __future__ import annotations

import json
import random
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
REPO_ROOT = THIS_DIR.parent.parent
sys.path.insert(0, str(REPO_ROOT / "contracts" / "schemas"))

from models.ai_fact_bundle import AIFactBundle  # noqa: E402
from models.api_envelopes import (  # noqa: E402
    BarsResponse,
    DerivedMetric,
    FundamentalsResponse,
    StrategiesResponse,
    StrategyEvaluateResponse,
    SymbolsResponse,
)
from models.common import Levels, Provenance  # noqa: E402
from models.financial_observation import FinancialObservation  # noqa: E402
from models.money_flow import MoneyFlowBlock  # noqa: E402
from models.security_master import SecurityMaster  # noqa: E402
from models.strategy_definition import StrategyDefinition  # noqa: E402
from models.strategy_evaluation_result import StrategyEvaluationResult  # noqa: E402

OUT_DIR = THIS_DIR
CONTRACT_VERSION = (REPO_ROOT / "contracts" / "VERSION").read_text().strip()
DATA_VERSION = "fdata-2026-07-30"
AS_OF_DATE = date(2026, 7, 30)
INGESTED_AT = datetime(2026, 7, 30, 21, 30, 0, tzinfo=timezone(timedelta(hours=7)))
N_BARS = 520  # >= 500 required by deliverable 4

SYNTHETIC_WARNING = (
    "SYNTHETIC FIXTURE DATA. Generated by contracts/fixtures/generate_fixtures.py "
    "for contract development only; not sourced from any real feed. Only the "
    "final bar (2026-07-30), where present, matches the verified example in "
    "Section 10.1 of vn_terminal_multi_ai_development_plan.md v1.1."
)


def trading_dates(end: date, n: int) -> list[date]:
    """Business days ending at `end`, most recent last.

    Does not exclude Vietnamese public holidays (only weekends), since this
    is synthetic fixture data, not a real trading calendar. WP1's real
    FData adapter must use the actual file dates, not this approximation.
    """
    out: list[date] = []
    d = end
    while len(out) < n:
        if d.weekday() < 5:  # Mon-Fri
            out.append(d)
        d -= timedelta(days=1)
    out.reverse()
    return out


def synth_bars(
    symbol: str,
    exchange: str,
    anchor_close: float,
    anchor_open: float,
    anchor_high: float,
    anchor_low: float,
    anchor_volume: int,
    seed: int,
    n: int = N_BARS,
) -> list[dict]:
    rng = random.Random(seed)
    dates = trading_dates(AS_OF_DATE, n)

    # Build the close-price path backward from the anchor (last) day so the
    # final bar can equal the anchor exactly, then walk forward to derive
    # open/high/low/volume for every bar including the anchor day.
    closes = [0.0] * n
    closes[-1] = anchor_close
    for i in range(n - 2, -1, -1):
        pct = rng.gauss(0, 0.016)
        pct = max(min(pct, 0.07), -0.07)  # crude daily move cap
        prev_close = closes[i + 1] / (1 + pct)
        closes[i] = max(round(prev_close, 2), 1.0)

    bars = []
    prev_close = closes[0] * (1 - rng.gauss(0, 0.01))
    for i, d in enumerate(dates):
        close = closes[i]
        if i == n - 1:
            o, h, low, vol = anchor_open, anchor_high, anchor_low, anchor_volume
        else:
            o = round(prev_close * (1 + rng.gauss(0, 0.004)), 2)
            spread = abs(rng.gauss(0, 0.012)) * close
            h = round(max(o, close) + spread, 2)
            low = round(max(min(o, close) - spread, 0.1), 2)
            vol = int(max(rng.gauss(3_000_000, 1_200_000), 50_000))
        bars.append(
            {
                "symbol": symbol,
                "exchange": exchange,
                "security_type": "equity",
                "timeframe": "1D",
                "trading_date": d.isoformat(),
                "timezone": "Asia/Ho_Chi_Minh",
                "open": o,
                "high": h,
                "low": low,
                "close": close,
                "volume": vol,
                "adjustment_status": "adjusted_unknown_method",
                "source": "Fialda FData",
                "source_file": f"C:\\FDATA\\AmiBroker\\EOD\\stock\\{symbol}.dat",
                "ingested_at": INGESTED_AT.isoformat(),
                "quality_status": "valid",
            }
        )
        prev_close = close
    return bars


def provenance(warnings: list[str] | None = None) -> Provenance:
    return Provenance(
        as_of_date=AS_OF_DATE,
        data_version=DATA_VERSION,
        source="Fialda FData",
        freshness_status="current",
        warnings=warnings or [],
    )


def build_bars_fixture(symbol: str, exchange: str, **kw) -> dict:
    bars = synth_bars(symbol, exchange, **kw)
    resp = BarsResponse(
        symbol=symbol,
        timeframe="1D",
        bars=bars,
        provenance=provenance([SYNTHETIC_WARNING]),
    )
    return json.loads(resp.model_dump_json())


def build_fundamentals_fixture(symbol: str, seed: int) -> dict:
    rng = random.Random(seed)
    observations = []
    metrics = []
    revenue = rng.uniform(3000, 20000)  # billion VND scale, illustrative only
    for i in range(12, 0, -1):  # 12 quarters back
        q_end = date(2026, 6, 30) - timedelta(days=91 * i)
        # normalize to end-of-quarter-ish
        q_end = date(q_end.year, ((q_end.month - 1) // 3) * 3 + 3, 1) - timedelta(days=1)
        revenue *= 1 + rng.uniform(-0.03, 0.06)
        net_income = revenue * rng.uniform(0.08, 0.18)
        pub_date = q_end + timedelta(days=rng.randint(20, 40))
        has_pub_date = i != 3  # one quarter deliberately missing, degraded mode (Section 17)
        observations.append(
            FinancialObservation(
                symbol=symbol,
                period_end=q_end,
                period_type="quarter",
                statement_type="income_statement",
                metric_code="revenue",
                metric_label_vi="Doanh thu thuan",
                value=round(revenue, 2),
                currency="VND",
                unit="billion_vnd",
                consolidated=True,
                restatement_version=1,
                publication_date=pub_date if has_pub_date else None,
                source_url="https://vnstock.example/placeholder",
                ingested_at=INGESTED_AT,
            )
        )
        observations.append(
            FinancialObservation(
                symbol=symbol,
                period_end=q_end,
                period_type="quarter",
                statement_type="income_statement",
                metric_code="net_income",
                metric_label_vi="Loi nhuan sau thue",
                value=round(net_income, 2),
                currency="VND",
                unit="billion_vnd",
                consolidated=True,
                restatement_version=1,
                publication_date=pub_date if has_pub_date else None,
                source_url="https://vnstock.example/placeholder",
                ingested_at=INGESTED_AT,
            )
        )
    metrics.append(
        DerivedMetric(
            symbol=symbol,
            period_end=observations[-2].period_end,
            metric_code="net_margin",
            metric_label_vi="Bien loi nhuan rong",
            value=round(observations[-1].value / observations[-2].value, 4),
            unit="ratio",
        )
    )
    metrics.append(
        DerivedMetric(
            symbol=symbol,
            period_end=observations[-2].period_end,
            metric_code="revenue_yoy_growth",
            metric_label_vi="Tang truong doanh thu YoY",
            value=round(rng.uniform(-0.05, 0.25), 4),
            unit="ratio",
        )
    )
    resp = FundamentalsResponse(
        symbol=symbol,
        observations=observations,
        derived_metrics=metrics,
        provenance=provenance(
            [
                SYNTHETIC_WARNING,
                (
                    "One quarter's observations deliberately omit publication_date "
                    "to exercise the Section 17 degraded-mode path: available for "
                    "display and current screening, excluded from historical "
                    "backtests."
                ),
            ]
        ),
    )
    return json.loads(resp.model_dump_json())


def build_strategy_evaluation_fixture(symbol: str, signal: str, score: int, support: list, resistance: list, invalidation) -> dict:
    result = StrategyEvaluationResult(
        symbol=symbol,
        as_of_date=AS_OF_DATE,
        strategy_id="minervini_trend_template",
        strategy_version="1.0.0",
        signal=signal,
        score=score,
        max_score=8,
        passed_criteria=[
            "close_above_150d_sma",
            "close_above_200d_sma",
            "150d_sma_above_200d_sma",
        ],
        failed_criteria=["within_25pct_of_52w_high"],
        levels=Levels(support=support, resistance=resistance, invalidation=invalidation),
        data_version=DATA_VERSION,
        warnings=[],
    )
    resp = StrategyEvaluateResponse(
        results=[result],
        provenance=provenance(
            [
                SYNTHETIC_WARNING,
                (
                    "strategy_id 'minervini_trend_template' and its score/criteria "
                    "reuse the literal example from Section 10.5 of the plan; this "
                    "is a schema-shape fixture, not an approved v1.0 strategy "
                    "specification (see docs/strategy_catalogue.md)."
                ),
            ]
        ),
    )
    return json.loads(resp.model_dump_json())


def build_strategy_definitions_fixture() -> dict:
    """Shape-only fixture for /api/strategies. Not a real specification.

    See docs/decision_log.md, WP0 entry, "Do not populate
    docs/strategy_catalogue.md with concrete strategy rules." The same
    reasoning applies here: this fixture exists so the frontend can render
    the Strategies tab (Section 12.3) against a schema-valid object, not to
    pre-empt the user's Stream F specification work.
    """

    placeholder = (
        "PLACEHOLDER: not a real specification. Awaiting the user's Stream F "
        "specification session per Section 13.2 / docs/strategy_catalogue.md."
    )
    definition = StrategyDefinition(
        strategy_id="minervini_trend_template",
        version="1.0.0",
        title_vi="Mau hinh xu huong Minervini (cho vi du)",
        title_en="Minervini trend template (placeholder)",
        category="minervini_template",
        timeframe="1D",
        required_fields=["close", "volume", "sma_150", "sma_200", "52w_high"],
        warmup_bars=252,
        parameter_schema={"note": placeholder},
        entry_rule=placeholder,
        exit_rule=placeholder,
        invalidation_rule=placeholder,
        liquidity_rule=placeholder,
        execution_convention="next_open",
        evidence_fields=["passed_criteria", "failed_criteria", "score", "max_score"],
        reference="Section 10.5 example strategy_id; rules not yet specified by the user.",
    )
    resp = StrategiesResponse(
        strategies=[definition],
        provenance=provenance(
            [
                SYNTHETIC_WARNING,
                (
                    "Every rule field is a literal PLACEHOLDER string. This is a "
                    "schema-shape fixture, not an approved v1.0 strategy "
                    "catalogue; see docs/strategy_catalogue.md."
                ),
            ]
        ),
    )
    return json.loads(resp.model_dump_json())


def build_ai_fact_bundle_fixture(symbol: str, bars_resp: dict, fundamentals_resp: dict, eval_resp: dict) -> dict:
    last_bar = bars_resp["bars"][-1]
    prev_bar = bars_resp["bars"][-2]
    closes = [b["close"] for b in bars_resp["bars"][-20:]]
    up_days = sum(1 for i in range(1, len(closes)) if closes[i] >= closes[i - 1])
    down_days = len(closes) - 1 - up_days

    money_flow = MoneyFlowBlock(
        accumulation_distribution_line=round(sum(closes), 2),
        on_balance_volume=float(sum(b["volume"] for b in bars_resp["bars"][-20:])),
        up_down_volume_ratio=round((up_days + 1) / (down_days + 1), 3),
        volume_at_price_concentration={
            "note": "OPEN ITEM shape; see contracts/OPEN_ITEMS.md",
            "buckets": [],
        },
        unusual_volume_flags=[],
        close_vs_vwap=None,
    )

    bundle = AIFactBundle(
        symbol=symbol,
        as_of_date=AS_OF_DATE,
        price_summary={
            "last_close": last_bar["close"],
            "prev_close": prev_bar["close"],
            "change_abs": round(last_bar["close"] - prev_bar["close"], 2),
            "change_pct": round((last_bar["close"] - prev_bar["close"]) / prev_bar["close"], 4),
            "last_volume": last_bar["volume"],
            "note": "OPEN ITEM shape; see contracts/OPEN_ITEMS.md",
        },
        indicators={
            "note": "OPEN ITEM shape; see contracts/OPEN_ITEMS.md",
            "sma_20": round(sum(closes) / len(closes), 2),
        },
        money_flow=money_flow,
        strategy_results=[StrategyEvaluationResult(**eval_resp["results"][0])],
        financial_summary={
            "note": "OPEN ITEM shape; see contracts/OPEN_ITEMS.md",
            "latest_revenue": fundamentals_resp["observations"][-2]["value"],
            "latest_net_income": fundamentals_resp["observations"][-1]["value"],
        },
        levels=Levels(**eval_resp["results"][0]["levels"]),
        data_quality={
            "freshness_status": "current",
            "warnings": [SYNTHETIC_WARNING],
        },
        sources=["https://vnstock.example/placeholder"],
        calculation_definitions=[
            "sma_20: simple moving average of close over the trailing 20 trading days.",
        ],
    )
    return json.loads(bundle.model_dump_json())


def build_security_master_fixture() -> dict:
    fpt = SecurityMaster(
        symbol="FPT",
        isin=None,
        exchange="HOSE",
        security_type="equity",
        company_name="FPT Corporation",
        sector="Information Technology",
        industry="IT Services",
        listing_date=date(2006, 12, 13),
        delisting_date=None,
        trading_status="active",
        currency="VND",
        price_unit="thousand_vnd",
        lot_size=100,
        source="fixture-placeholder",
        valid_from=date(2006, 12, 13),
        valid_to=None,
        index_code=None,
    )
    kdh = SecurityMaster(
        symbol="KDH",
        isin=None,
        exchange="HOSE",
        security_type="equity",
        company_name="Khang Dien House Trading and Investment JSC",
        sector="Real Estate",
        industry="Real Estate Development",
        listing_date=date(2010, 7, 20),
        delisting_date=None,
        trading_status="active",
        currency="VND",
        price_unit="thousand_vnd",
        lot_size=100,
        source="fixture-placeholder",
        valid_from=date(2010, 7, 20),
        valid_to=None,
        index_code=None,
    )
    resp = SymbolsResponse(
        items=[fpt, kdh],
        total=2,
        provenance=provenance(
            [
                SYNTHETIC_WARNING,
                (
                    "company_name/sector/industry/listing_date are illustrative "
                    "placeholders, not verified against an official registry in "
                    "this session. WP2 must replace this fixture's contents with "
                    "real security-master data."
                ),
            ]
        ),
    )
    return json.loads(resp.model_dump_json())


def main() -> None:
    fpt_bars = build_bars_fixture(
        "FPT",
        "HOSE",
        anchor_close=67.0,
        anchor_open=65.2,
        anchor_high=67.2,
        anchor_low=64.8,
        anchor_volume=7_571_500,
        seed=20260730,
    )
    kdh_bars = build_bars_fixture(
        "KDH",
        "HOSE",
        anchor_close=38.5,
        anchor_open=38.0,
        anchor_high=38.9,
        anchor_low=37.8,
        anchor_volume=2_340_000,
        seed=20260731,
    )

    fpt_fund = build_fundamentals_fixture("FPT", seed=1001)
    kdh_fund = build_fundamentals_fixture("KDH", seed=1002)

    fpt_eval = build_strategy_evaluation_fixture(
        "FPT", signal="watch", score=6, support=[64.0, 61.5], resistance=[68.5, 71.0], invalidation=60.0
    )
    kdh_eval = build_strategy_evaluation_fixture(
        "KDH", signal="watch", score=5, support=[36.5, 34.8], resistance=[40.0, 42.5], invalidation=34.0
    )

    fpt_bundle = build_ai_fact_bundle_fixture("FPT", fpt_bars, fpt_fund, fpt_eval)
    kdh_bundle = build_ai_fact_bundle_fixture("KDH", kdh_bars, kdh_fund, kdh_eval)

    strategy_definitions = build_strategy_definitions_fixture()
    security_master = build_security_master_fixture()

    files = {
        "bars_FPT.json": fpt_bars,
        "bars_KDH.json": kdh_bars,
        "fundamentals_FPT.json": fpt_fund,
        "fundamentals_KDH.json": kdh_fund,
        "strategy_evaluation_FPT.json": fpt_eval,
        "strategy_evaluation_KDH.json": kdh_eval,
        "ai_fact_bundle_FPT.json": fpt_bundle,
        "ai_fact_bundle_KDH.json": kdh_bundle,
        "strategy_definitions.json": strategy_definitions,
        "security_master.json": security_master,
    }

    for name, payload in files.items():
        out_path = OUT_DIR / name
        out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
        print(f"Wrote {name} ({len(json.dumps(payload))} bytes)")

    assert len(fpt_bars["bars"]) >= 500
    assert len(kdh_bars["bars"]) >= 500
    assert fpt_bars["bars"][-1]["open"] == 65.2
    assert fpt_bars["bars"][-1]["high"] == 67.2
    assert fpt_bars["bars"][-1]["low"] == 64.8
    assert fpt_bars["bars"][-1]["close"] == 67.0
    assert fpt_bars["bars"][-1]["volume"] == 7_571_500
    print("All sanity checks passed (>=500 bars/symbol; FPT anchor bar matches Section 10.1).")


if __name__ == "__main__":
    main()
